# Generated by Django 3.2.4 on 2021-09-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewedproduct',
            name='is_seen',
            field=models.IntegerField(default=0, verbose_name='وضعیت مشاهده'),
        ),
    ]
