# Generated by Django 3.2.4 on 2021-12-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_orders', '0003_auto_20211227_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='active',
        ),
        migrations.AddField(
            model_name='discount',
            name='use',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
