# Generated by Django 3.2.4 on 2021-12-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_categories', '0001_initial'),
        ('eshop_orders', '0005_discountset_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountset',
            name='product_category',
            field=models.ManyToManyField(limit_choices_to=1, to='eshop_product_categories.ProductCategory'),
        ),
    ]
