# Generated by Django 3.2.4 on 2021-09-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='عنوان')),
                ('subject', models.CharField(max_length=150, verbose_name='عنوان')),
                ('text', models.TextField(max_length=1000, verbose_name='توضیحات')),
                ('email', models.EmailField(max_length=254, verbose_name='توضیحات')),
                ('is_read', models.BooleanField(default=False, verbose_name='خواند شده/ خواند نشده')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس ها',
            },
        ),
    ]
