# Generated by Django 3.2.4 on 2021-09-18 15:39

from django.db import migrations, models
import eshop_sliders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('link', models.URLField(max_length=300, verbose_name='ادرس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=eshop_sliders.models.slider_image_directory_path, verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
    ]
