# Generated by Django 3.2.4 on 2021-09-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='شماره مویایل')),
                ('company_number', models.CharField(blank=True, max_length=50, verbose_name='شماره تلفن')),
                ('about_us', models.TextField(blank=True, verbose_name='توضیحات')),
                ('track', models.CharField(blank=True, max_length=300, verbose_name='ادرس')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'تنظیم',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
